---
- name: Launch Interface custom resource build jobs (CR only)
  nokia.eda_interfaces_v1alpha1.interface:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource:
      metadata:
        namespace: "{{ eda_namespace }}"
        name: "{{ item.name }}"
        labels:
          demo.nokia.com/source: "uv-ansible-toponodes"
      spec:
        description: "{{ item.description | default(omit) }}"
        type: "{{ item.type | default('interface') }}"
        members: "{{ item.members }}"
  loop: "{{ topolink_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: interface_cr_jobs

- name: Wait for Interface custom resource builds to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: interface_crs
  until: interface_crs.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ interface_cr_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"
