---
- name: Launch NodeProfile custom resource build jobs (CR only)
  nokia.eda_apps_core_v1.nodeprofile:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource:
      metadata:
        namespace: "{{ eda_namespace }}"
        name: "{{ item.value.name }}"
        labels:
          demo.nokia.com/source: "uv-ansible-toponodes"
      spec: "{{ item.value.spec | combine({}) }}"
  loop: "{{ nodeprofiles | dict2items }}"
  loop_control:
    label: "{{ item.value.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: nodeprofile_cr_jobs

- name: Wait for NodeProfile custom resource builds to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: nodeprofile_crs
  until: nodeprofile_crs.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ nodeprofile_cr_jobs.results }}"
  loop_control:
    label: "{{ item.item.value.name }}"
