---
- name: Launch TopoLink custom resource build jobs (CR only)
  nokia.eda_apps_core_v1.topolink:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource:
      metadata:
        namespace: "{{ eda_namespace }}"
        name: "{{ item.name }}"
        labels:
          demo.nokia.com/source: "uv-ansible-toponodes"
      spec:
        links: "{{ item.links }}"
  loop: "{{ topolinks }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: topolink_cr_jobs

- name: Wait for TopoLink custom resource builds to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: topolink_crs
  until: topolink_crs.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ topolink_cr_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"
