---
- name: Build TopoLink custom resources (CR only)
  nokia.eda_apps_core_v1.topolink:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource: >-
      {{ lookup('ansible.builtin.template', playbook_dir ~ '/templates/topolink_resource.json.j2') | from_json }}
  loop: "{{ topolinks }}"
  loop_control:
    label: "{{ item.name }}"
  register: topolink_crs
