---
- name: Launch TopoNode custom resource build jobs (CR only)
  nokia.eda_apps_core_v1.toponode:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource:
      metadata:
        namespace: "{{ eda_namespace }}"
        name: "{{ item.name }}"
        labels:
          eda.nokia.com/role: "{{ item.role }}"
          demo.nokia.com/source: "uv-ansible-toponodes"
      spec:
        nodeProfile: "{{ item.node_profile }}"
        operatingSystem: "{{ item.operating_system | default('srl') }}"
        platform: "{{ item.platform }}"
        version: "{{ item.version }}"
        productionAddress: >-
          {{ {'ipv4': item.production_ipv4} if item.production_ipv4 is defined else omit }}
  loop: "{{ toponodes }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: topo_cr_jobs

- name: Launch TopoNode discovery jobs
  nokia.eda_apps_core_v1.toponode:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: query
    namespace: "{{ eda_namespace }}"
    name: "{{ item.name }}"
  loop: "{{ toponodes }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: existing_toponode_jobs
  failed_when: false

- name: Wait for TopoNode custom resource builds to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: topo_crs
  until: topo_crs.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ topo_cr_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Wait for TopoNode discovery jobs to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: existing_toponodes
  until: existing_toponodes.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ existing_toponode_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  failed_when: false

- name: Fail if TopoNode lookup returned unexpected errors
  ansible.builtin.fail:
    msg: >-
      Failed to query TopoNode {{ lookup_name }}: {{ lookup_msg }}
  when:
    - lookup_payload.failed | default(item.failed | default(false))
    - (lookup_msg_text | lower | regex_search('not found')) is none
  loop: "{{ existing_toponodes.results }}"
  loop_control:
    label: "{{ lookup_name }}"
  vars:
    lookup_payload: "{{ item.result | default(item) }}"
    lookup_msg: >-
      {{
        lookup_payload.msg
        | default(
          lookup_payload.body
          | default(item.msg | default(item.body | default(item)))
        )
      }}
    lookup_msg_text: "{{ lookup_msg | string }}"
    lookup_name: "{{ item.item.item.name | default(item.item.item | default('unknown')) }}"
