---
- name: Launch TopoLink custom resource build jobs (CR only)
  nokia.eda_apps_core_v1.topolink:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: cronly
    resource:
      metadata:
        namespace: "{{ eda_namespace }}"
        name: "{{ item.name }}"
        labels:
          demo.nokia.com/source: "uv-ansible-toponodes"
      spec:
        links: "{{ item.links }}"
  loop: "{{ topolinks }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: topolink_cr_jobs

- name: Launch TopoLink discovery jobs
  nokia.eda_apps_core_v1.topolink:
    base_url: "{{ eda_api_url }}"
    auth_token: "{{ eda_auth_token }}"
    tls_skip_verify: "{{ tls_skip_verify | bool }}"
    state: query
    namespace: "{{ eda_namespace }}"
    name: "{{ item.name }}"
  loop: "{{ topolinks }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ eda_async_timeout | default(120) | int }}"
  poll: 0
  register: existing_topolink_jobs
  failed_when: false

- name: Wait for TopoLink custom resource builds to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: topolink_crs
  until: topolink_crs.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ topolink_cr_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Wait for TopoLink discovery jobs to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: existing_topolinks
  until: existing_topolinks.finished
  retries: "{{ eda_async_retries | default(120) | int }}"
  delay: "{{ eda_async_delay | default(1) | int }}"
  loop: "{{ existing_topolink_jobs.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  failed_when: false

- name: Fail if TopoLink lookup returned unexpected errors
  ansible.builtin.fail:
    msg: >-
      Failed to query TopoLink {{ lookup_name }}: {{ lookup_msg }}
  when:
    - lookup_payload.failed | default(item.failed | default(false))
    - (lookup_msg_text | lower | regex_search('not found')) is none
  loop: "{{ existing_topolinks.results }}"
  loop_control:
    label: "{{ lookup_name }}"
  vars:
    lookup_payload: "{{ item.result | default(item) }}"
    lookup_msg: >-
      {{
        lookup_payload.msg
        | default(
          lookup_payload.body
          | default(item.msg | default(item.body | default(item)))
        )
      }}
    lookup_msg_text: "{{ lookup_msg | string }}"
    lookup_name: "{{ item.item.item.name | default(item.item.item | default('unknown')) }}"
