---
edge_interfaces:
  - name: edge-demo-leaf-1-ethernet-1-1
    namespace: eda
    labels:
      eda.nokia.com/macvrf201: "true"
      eda.nokia.com/macvrf1001: "true"
      eda.nokia.com/role: edge
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        speed: 10G
      members:
        - enabled: true
          interface: ethernet-1-1
          node: demo-leaf-1
      type: interface
  - name: edge-demo-leaf-2-ethernet-1-1
    namespace: eda
    labels:
      eda.nokia.com/macvrf202: "true"
      eda.nokia.com/macvrf1001: "true"
      eda.nokia.com/role: edge
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        speed: 10G
      members:
        - enabled: true
          interface: ethernet-1-1
          node: demo-leaf-2
      type: interface
  - name: edge-demo-leaf-3-ethernet-1-1
    namespace: eda
    labels:
      eda.nokia.com/macvrf201: "true"
      eda.nokia.com/macvrf1001: "true"
      eda.nokia.com/role: edge
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        speed: 10G
      members:
        - enabled: true
          interface: ethernet-1-1
          node: demo-leaf-3
      type: interface
  - name: edge-demo-leaf-4-ethernet-1-1
    namespace: eda
    labels:
      eda.nokia.com/macvrf202: "true"
      eda.nokia.com/macvrf1001: "true"
      eda.nokia.com/role: edge
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        speed: 10G
      members:
        - enabled: true
          interface: ethernet-1-1
          node: demo-leaf-4
      type: interface

virtual_networks:
  - name: macvrf1001
    namespace: eda
    spec:
      bridgeDomains:
        - name: macvrf1001
          spec:
            eviPool: evi-pool
            macAging: 300
            macLearning: true
            tunnelIndexPool: tunnel-index-pool
            type: EVPNVXLAN
            vniPool: vni-pool
      vlans:
        - name: macvrf1001
          spec:
            bridgeDomain: macvrf1001
            interfaceSelector:
              - eda.nokia.com/macvrf1001
            vlanID: "1001"
